In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

### Numpy

The goal of this notebook is to collect all frequently (or not that frequently) used capabilities of *numpy*.

## Arrays and indexing

### Creation

#### From python list

One can create a numpy array from usual python list

In [3]:
arr = [1,2,3,4,5]
np.array(arr) # now it's a numpy array

array([1, 2, 3, 4, 5])

Same works for matrices

In [4]:
matrix = [[1,2,3], [4,5,6], [7,8,9]]
np.array(matrix) # now it's a two-dimensional numpy array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

And even for higher dimensions

In [5]:
tensor = [
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15], [16,17,18]]
]
np.array(tensor) # now it's a three-dimensional numpy array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

#### Data types

It's possible to specify the type of array's elements via *dtype* argument

In [6]:
arr = [1,2,3,4,5]
np.array(arr, dtype=int)

array([1, 2, 3, 4, 5])

In [7]:
arr = [1,2,3,4,5]
np.array(arr, dtype=float)

array([1., 2., 3., 4., 5.])

In [8]:
arr = [1,2,3,4,5]
np.array(arr, dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [9]:
arr = [0,1,2,3,4,5]
np.array(arr, dtype=bool)

array([False,  True,  True,  True,  True,  True])

If the type is not given, it will be determined as the minimum type required to hold the objects in the sequence.

In [10]:
arr = [1,2,3,4,5,6.]
np.array(arr)

array([1., 2., 3., 4., 5., 6.])

In [11]:
print(np.array(arr).dtype)

float64


#### Minimum number of dimensions

One can specify minimum number of dimensions with optional *ndmin* argument. Ones will be pre-pended to the shape as needed to meet this requirement.

In [12]:
np.array([1,2,3], ndmin=2)

array([[1, 2, 3]])