In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.4'

### Numpy

The goal of this notebook is to collect all frequently (or not that frequently) used capabilities of *numpy*.

## Arrays and indexing

### Creation

#### From python list

One can create a numpy array from usual python list

In [3]:
arr = [1,2,3,4,5]
np.array(arr) # now it's a numpy array

array([1, 2, 3, 4, 5])

Same works for matrices

In [4]:
matrix = [[1,2,3], [4,5,6], [7,8,9]]
np.array(matrix) # now it's a two-dimensional numpy array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

And even for higher dimensions

In [5]:
tensor = [
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15], [16,17,18]]
]
np.array(tensor) # now it's a three-dimensional numpy array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

##### Data types

It's possible to specify the type of array's elements via *dtype* argument

In [6]:
arr = [1,2,3,4,5]
np.array(arr, dtype=int)

array([1, 2, 3, 4, 5])

In [7]:
arr = [1,2,3,4,5]
np.array(arr, dtype=float)

array([1., 2., 3., 4., 5.])

In [8]:
arr = [1,2,3,4,5]
np.array(arr, dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [9]:
arr = [0,1,2,3,4,5]
np.array(arr, dtype=bool)

array([False,  True,  True,  True,  True,  True])

If the type is not given, it will be determined as the minimum type required to hold the objects in the sequence.

In [10]:
arr = [1,2,3,4,5,6.]
np.array(arr)

array([1., 2., 3., 4., 5., 6.])

In [11]:
print(np.array(arr).dtype)

float64


##### Minimum number of dimensions

One can specify minimum number of dimensions with optional *ndmin* argument. Ones will be pre-pended to the shape as needed to meet this requirement.

In [12]:
np.array([1,2,3], ndmin=2)

array([[1, 2, 3]])

#### Numpy methods

##### arange

*np.arange* generates an evenly spaced sequence of numbers within a given interval

In [13]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Start can be omitted

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

One may specify a step and/or a dtype

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [34]:
np.arange(0, 10, 2.5, dtype='complex')

array([0. +0.j, 2.5+0.j, 5. +0.j, 7.5+0.j])

##### linspace

Generates evenly spaces numbers over the interval. Here one can set the number of points in the sequence. Sometimes might be easier than specifiying the step for *np.arange* 

In [33]:
np.linspace(0, 5, num=10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Endpoint can be excluded

In [35]:
np.linspace(0, 5, num=10, endpoint=False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

*retstep* parameter indicates if the step should be returned 

In [36]:
np.linspace(0, 5, num=10, endpoint=False, retstep=True)

(array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]), 0.5)

##### zeros

*np.zeros* generates a vector/matrix/tensor filled with zeros

In [20]:
np.zeros(~5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.zeros((2,5,5), dtype=int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

It's possible to specify how to store the matrix in memory: either row-wise (C-style) or column-wise (Fortran-style)

In [25]:
np.zeros((2,2), order='C')

array([[0., 0.],
       [0., 0.]])

In [26]:
np.zeros((2,2), order='F')

array([[0., 0.],
       [0., 0.]])

##### ones

*np.ones* generates a vector/matrix/tensor filled with ones

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.ones((2,3,4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

##### eye

Creates an identity matrix

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [40]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

It's possible to "shift" the main diagonal with *k* parameter. Positive *k* shifts the diagonal to the top, negative -- to the bottom.

In [41]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [42]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [45]:
# Not very elegant way to construct a matrix containing ones only
result = np.zeros((4,4))
for k in range(-4, 5):
    result += np.eye(4, k=k)
result

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

*np.identity* method does almost the same as *np.eye* but it's not that flexible  

In [48]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##### linspace

*np.linspace(start, end, n)* returns $n$ evenly spaced points between $start$ and $end$. Might be a good idea to use when you know number of points beforehead.

In [6]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Random

##### rand

Generates a random array of given shape. Numbers are uniformly distributed on $[0,1]$ interval.

Just get a random number between $0$ and $1$:

In [8]:
np.random.rand()

0.5336601020160713

In [10]:
np.random.rand(5)

array([0.83140161, 0.10802696, 0.06019138, 0.97054299, 0.90981527])

You should pass shape **not** as a tuple, but as positional arguments

In [14]:
np.random.rand(2, 3)

array([[0.91905857, 0.81243098, 0.90357918],
       [0.46531902, 0.31608138, 0.97967013]])

In [15]:
np.random.rand(2,2,2)

array([[[0.877185  , 0.65269641],
        [0.46148512, 0.0348458 ]],

       [[0.98869685, 0.19142172],
        [0.3019783 , 0.2168086 ]]])

Do this if you want to get a random number uniformly distributed on $[a, b]$, $length = b - a$

In [22]:
length = 5
a = 2
# random number on [2, 7]
length * np.random.rand() + a

6.694054822668445

In [23]:
length = 2
a = -1
# random array on [-1, 1]
length * np.random.rand(5) + a

array([ 0.25097112,  0.39415707,  0.09580908, -0.85405541,  0.319971  ])

##### randn

Use *np.random.randn* if you want to generate random numbers with Gaussian (standard normal) distribution $\mathcal{N}(0, 1)$

In [25]:
np.random.randn()

2.0295631739789934

In [26]:
np.random.randn(2,3)

array([[ 0.44986483, -0.87395278, -0.47551956],
       [ 0.46565277, -0.31012793, -1.07106652]])

To generate numbers from $\mathcal{N}(\mu, \sigma^2)$ use this

In [30]:
mu = 3
sigma = 2

# random number from Gaussian distribution with mean=3 and variance=2
sigma * np.random.randn() + mu

3.561068675010647

In [32]:
mu = 3
sigma = 2

# random array from Gaussian distribution with mean=3 and variance=2
sigma * np.random.randn(5) + mu

array([1.2050529 , 3.83352613, 1.28423957, 1.88883239, 4.99000956])

##### randint

In [33]:
np.random.randint(1, 100, 10)

array([39, 56, 38, 31, 56, 87, 26,  9, 91, 21])